default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: aircall_backend_development

test:
  <<: *default
  database: aircall_backend_test

production:
  <<: *default
  database: aircall_backend_production
